image: registry.gitlab.com/wut-pw/dyplom-pro

pages:
  stage: deploy
  script:
  - ./configure
  - mkdir public
  - cp index.html out.pdf public
  - make
  artifacts:
    paths:
    - public
  only:
  - master
