image: rocker/verse

pages:
  stage: deploy
  script:
  #- pip3 install --user `cat pydeps`
  #- make
  - echo "$GITLAB_USER_LOGIN ALL=(ALL) NOPASSWD:ALL" | tee --append /etc/sudoers
  - useradd --create-home "$GITLAB_USER_LOGIN"
  - su "$GITLAB_USER_LOGIN"
  - mkdir public
  - cp index.html out.pdf public
  - ./configure
  artifacts:
    paths:
    - public
  only:
  - master
