image: registry.gitlab.com/wut-pw/dyplom-pro

pages:
  stage: deploy
  script:
  - mkdir public && src/generate && cp src/index.html out.pdf public
  artifacts:
    paths:
    - public
  only:
  - master
