stages:
  - build
  - pages

build_docker_image:
  stage: build
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_KEY
    - docker build --layers -t registry.gitlab.com/wut-pw/dyplom-pro - < src/Dockerfile
    - docker push registry.gitlab.com/wut-pw/dyplom-pro
  only:
    changes:
      - .gitlab-ci.yml
      - src/Dockerfile

pages:
  stage: pages
  image: registry.gitlab.com/wut-pw/dyplom-pro
  script:
  - mkdir public && src/generate && cp src/index.html out.pdf public
  artifacts:
    paths:
    - public
  only:
  - master
