image: ubuntu:latest

pages:
  stage: deploy
  script:
  #- pip3 install --user `cat pydeps`
  #- make
  - apt-get update && apt-get install -y sudo
  - echo "$GITLAB_USER_LOGIN ALL=(ALL) NOPASSWD:ALL" | tee --append /etc/sudoers
  - useradd --create-home "$GITLAB_USER_LOGIN"
  - mkdir public
  - cp index.html out.pdf public
  - sudo -u "$GITLAB_USER_LOGIN" ./configure
  artifacts:
    paths:
    - public
  only:
  - master
