image: ubuntu:latest

pages:
  stage: deploy
  script:
  - ./setup_container
  - ./configure
  - mkdir public
  - cp index.html out.pdf public
  - make
  artifacts:
    paths:
    - public
  only:
  - master
