#!/usr/bin/env bash

out=${1:-out.pdf}
personal_dir=${2:-personal}

pandoc \
	--listings \
	-f markdown \
	--filter=pandoc-xnos \
	--bibliography="$personal_dir"/bib/dsr.bib \
	--bibliography="$personal_dir"/bib/architecture.bib \
	--bibliography="$personal_dir"/bib/practical_measurement.bib \
	--top-level-division=chapter \
	--resource-path=:"$personal_dir":"$personal_dir"/infocard \
  --metadata xnos-warning-level=1 \
	"$personal_dir"/meta.yaml \
	"$personal_dir"/labels.tex \
	frontmatter.tex \
	"$personal_dir"/*.md \
	--pdf-engine=lualatex \
	-t latex \
	-o "$out"
