#!/usr/bin/env bash

USER=${GITLAB_USER_LOGIN:-user}

prepare_container() {
  # Configure timezone to install sudo without warnings.
  TZ=Europe/Warsaw && ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime && echo "$TZ" > /etc/timezone

  apt-get update && apt-get install -y sudo curl git make python3-pip wget axel

  echo "$USER ALL=(ALL) NOPASSWD:ALL" | tee --append /etc/sudoers

  useradd --create-home "$USER"
}

switch_user() {
  su --login "$USER"
}

prepare_container

switch_user
