#!/usr/bin/env bash

location=$(readlink -f "$0")
install_dir=$(readlink -f $(dirname $location))

podman run \
  --rm -it --privileged \
  -v "$install_dir"/..:/usr/local/share/dyplom_pro:ro \
  ubuntu:latest \
  /bin/bash
