#!/usr/bin/env bash

src_path=$(cd "$(dirname "$0")"; pwd)

personal_dir=${2:-"$src_path"/..}
out=${1:-"$personal_dir"/out.pdf}

(cd "$personal_dir" \
  && pandoc \
    --listings \
    -f markdown \
    --filter=pandoc-xnos \
    --bibliography=bib/dsr.bib \
    --bibliography=bib/architecture.bib \
    --bibliography=bib/practical_measurement.bib \
    --top-level-division=chapter \
    --metadata xnos-warning-level=1 \
    meta.yaml \
    labels.tex \
    "$src_path"/frontmatter.tex \
    tresc.md \
    --pdf-engine=lualatex \
    -t latex \
    -o "$out")
